-------------------------------------- SECUENCIAS --------------------------------------
CREATE SEQUENCE RUBRO_SEQ;
CREATE SEQUENCE TIPO_DOC_SEQ;
CREATE SEQUENCE FAMILIA_PRODUCTO_SEQ;
CREATE SEQUENCE TIPO_PRODUCTO_SEQ;
CREATE SEQUENCE ORDEN_SEQ;
CREATE SEQUENCE ORDEN_DETALLE_SEQ;
CREATE SEQUENCE RECIBO_SEQ;
CREATE SEQUENCE MARCA_SEQ;
CREATE SEQUENCE PROVEEDOR_SEQ START WITH 100;
CREATE SEQUENCE PRODUCTO_SEQ;
CREATE SEQUENCE DOMICILIO_SEQ;
CREATE SEQUENCE TIPO_ORDEN_SEQ;
CREATE SEQUENCE ESTADO_SEQ;
CREATE SEQUENCE NOTA_CREDITO_SEQ;
CREATE SEQUENCE NOTA_CREDITO_DETALLE_SEQ;
CREATE SEQUENCE MOTIVO_SEQ;
CREATE SEQUENCE DELIVERY_SEQ;

------------------------------- INSERTS DE DATOS PREDEFINIDOS -------------------------------
-- MOTIVOS CANCELACION COMPRA
INSERT INTO MOTIVO VALUES(MOTIVO_SEQ.NEXTVAL, 'No llegó en el periodo acordado');
INSERT INTO MOTIVO VALUES(MOTIVO_SEQ.NEXTVAL, 'Producto defectuoso');
INSERT INTO MOTIVO VALUES(MOTIVO_SEQ.NEXTVAL, 'Otro');

-- ESTADO ORDEN COMPRA
INSERT INTO ESTADO VALUES(ESTADO_SEQ.NEXTVAL, 'Pendiente');
INSERT INTO ESTADO VALUES(ESTADO_SEQ.NEXTVAL, 'Aprobado');
INSERT INTO ESTADO VALUES(ESTADO_SEQ.NEXTVAL, 'Rechazado');

-- TIPO ORDEN
INSERT INTO TIPO_ORDEN VALUES(TIPO_ORDEN_SEQ.NEXTVAL, 'Cliente');
INSERT INTO TIPO_ORDEN VALUES(TIPO_ORDEN_SEQ.NEXTVAL, 'Proveedor');

--RUBRO
INSERT INTO RUBRO VALUES(RUBRO_SEQ.NEXTVAL, 'Agricultura, Ganadería, Caza y Silvicultura');
INSERT INTO RUBRO VALUES(RUBRO_SEQ.NEXTVAL, 'Pesca');
INSERT INTO RUBRO VALUES(RUBRO_SEQ.NEXTVAL, 'Explotación de Minas y Canteras');
INSERT INTO RUBRO VALUES(RUBRO_SEQ.NEXTVAL, 'Industrias Manufactureras No Metálicas');
INSERT INTO RUBRO VALUES(RUBRO_SEQ.NEXTVAL, 'Industrias Manufactureras Metálicas');
INSERT INTO RUBRO VALUES(RUBRO_SEQ.NEXTVAL, 'Suministro de Electricidad, Gas y Agua');
INSERT INTO RUBRO VALUES(RUBRO_SEQ.NEXTVAL, 'Construcción');
INSERT INTO RUBRO VALUES(RUBRO_SEQ.NEXTVAL, 'Comercio al por Mayor y Menor, Rep. Veh. Automotores / Enseres Domésticos');
INSERT INTO RUBRO VALUES(RUBRO_SEQ.NEXTVAL, 'Hoteles y Restaurantes');
INSERT INTO RUBRO VALUES(RUBRO_SEQ.NEXTVAL, 'Transporte, Almacenamiento y Comunicaciones');
INSERT INTO RUBRO VALUES(RUBRO_SEQ.NEXTVAL, 'Intermediación Financiera');
INSERT INTO RUBRO VALUES(RUBRO_SEQ.NEXTVAL, 'Actividades Inmobiliarias, Empresariales y de Alquiler');
INSERT INTO RUBRO VALUES(RUBRO_SEQ.NEXTVAL, 'Adm. Pública y Defensa, Planes de Seg. Social Afiliación Obligatoria');
INSERT INTO RUBRO VALUES(RUBRO_SEQ.NEXTVAL, 'Enseñanza');
INSERT INTO RUBRO VALUES(RUBRO_SEQ.NEXTVAL, 'Servicios Sociales y de Salud');
INSERT INTO RUBRO VALUES(RUBRO_SEQ.NEXTVAL, 'Otras Actividades de Servicios Comunitarias, Sociales y Personales');
INSERT INTO RUBRO VALUES(RUBRO_SEQ.NEXTVAL, 'Consejo De Administración de Edificios y Condominios');
INSERT INTO RUBRO VALUES(RUBRO_SEQ.NEXTVAL, 'Organizaciones Y Órganos Extraterritoriales');
INSERT INTO RUBRO VALUES(RUBRO_SEQ.NEXTVAL, 'Otros rubros');

-- TIPO DOCUMENTO
INSERT INTO TIPO_DOCUMENTO VALUES(TIPO_DOC_SEQ.NEXTVAL, 'Boleta');
INSERT INTO TIPO_DOCUMENTO VALUES(TIPO_DOC_SEQ.NEXTVAL, 'Factura');

-- FAMILIA PRODUCTO / TIPO
INSERT INTO FAMILIA_PRODUCTO VALUES(FAMILIA_PRODUCTO_SEQ.NEXTVAL, 'Construcción', 'product-family/construccion.jpg');
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'ESTRUCTURA Y TABIQUERÍA', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'CUBIERTAS', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'EVACUACION', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'UTILES DE CONSTRUCCIÓN', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'AISLAMIENTO E IMPERMEABILIZACIÓN', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'TECHOS', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'PAVIMENTOS', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'PUERTAS', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'VENTANAS', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'ESCALERAS', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'REVESTIMIENTOS', FAMILIA_PRODUCTO_SEQ.CURRVAL);

INSERT INTO FAMILIA_PRODUCTO VALUES(FAMILIA_PRODUCTO_SEQ.NEXTVAL, 'Madera', 'product-family/madera.png');
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'MADERA ACABADOS', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'TABLEROS Y TABLAS', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'REVESTIMIENTO DE SUELO', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'REVESTIMIENTO DE PARED/TECHO', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, ' ARMARIOS E INTERIORES DE ARMARIO', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    
INSERT INTO FAMILIA_PRODUCTO VALUES(FAMILIA_PRODUCTO_SEQ.NEXTVAL, 'Electricidad', 'product-family/electricidad.jpg');
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'CONFORT Y DOMÓTICA', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'PILAS', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'MATERIAL DE INSTALACIÓN', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'MECANISMOS', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'PEQUEÑO MATERIAL ELÉCTRICO', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'MULTIMEDIA', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'ILUMINACIÓN', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'BOMBILLAS Y TUBOS', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'ENERGÍAS RENOVABLES', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    
INSERT INTO FAMILIA_PRODUCTO VALUES(FAMILIA_PRODUCTO_SEQ.NEXTVAL, 'Herramientas', 'product-family/herramientas.jpg');
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'MAQUINARIA', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'MAQUINARIA CONSTRUCCIÓN', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'MAQUINARIA PARA METAL', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'MAQUINARIA PARA MADERA', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'HERRAMIENTA MANUAL', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'HERRAMIENTA ELÉCTRICA', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'HERRAMIENTA NEUMÁTICA', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'ACCESORIOS Y CONSUMIBLES DE HERRAMIENTAS', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'EQUIPOS DE PROTECCIÓN INDIVIDUAL', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'EQUIPOS DE TALLER', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'ORDENACION DE HERRAMIENTAS ', FAMILIA_PRODUCTO_SEQ.CURRVAL);    
    
INSERT INTO FAMILIA_PRODUCTO VALUES(FAMILIA_PRODUCTO_SEQ.NEXTVAL, 'Baño y fontanería', 'product-family/fontaneria.jpg');
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'APARATOS SANITARIOS', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'MAMPARAS', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'HIDROTERAPIA', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'ACCESORIOS Y COMPLEMENTOS DE BAÑO', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'MUEBLES DE BAÑO', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'GRIFERÍA', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'EVACUACIÓN', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'PRODUCCIÓN DE AGUA CALIENTE ', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'CONDUCCIÓN DE AGUA', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'TRATAMIENTO DE AGUA', FAMILIA_PRODUCTO_SEQ.CURRVAL);    
    
INSERT INTO FAMILIA_PRODUCTO VALUES(FAMILIA_PRODUCTO_SEQ.NEXTVAL, 'Cocina', 'product-family/cocina.jpg');
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'MUEBLE COCINA', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'ACCESORIOS Y COMPLEMENTOS DE COCINA', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'GRIFERÍA', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'LÍNEA BLANCA', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'PEQUEÑO APARATO ELECTRODOMÉSTICO', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'MENAJE', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    
INSERT INTO FAMILIA_PRODUCTO VALUES(FAMILIA_PRODUCTO_SEQ.NEXTVAL, 'Jardín', 'product-family/jardin.jpg');
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'CIERRE Y OCULTACIÓN', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'MAQUINARIA JARDÍN', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'TIERRAS Y FITOSANITARIOS', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'HERRAMIENTAS JARDÍN ', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'DECORACIÓN JARDÍN', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'MADERA JARDÍN ', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'MUEBLE JARDÍN ', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'AUXILIAR JARDÍN', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'PISCINA', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'PLANTA VIVA Y SEMILLA', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'RIEGO', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'CASETAS Y COBERTIZOS ', FAMILIA_PRODUCTO_SEQ.CURRVAL);

INSERT INTO FAMILIA_PRODUCTO VALUES(FAMILIA_PRODUCTO_SEQ.NEXTVAL, 'Ferretería', 'product-family/ferreteria.jpg');
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'CERRAJERÍA', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'HERRAJE PUERTA Y VENTANA', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'HERRAJE MUEBLE', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'CAJAS DE SEGURIDAD', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'FIJACIÓN', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'CABLES CADENAS Y CORDELERÍA', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'BUZONES', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'RUEDAS', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'ACCESORIOS DE AUTOMOCIÓN', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'PATAS', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'PERFILERÍA', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'TENDIDO Y PLANCHADO', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'PERCHAS, COLGADORES Y GANCHOS', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'SEÑALIZACIÓN', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'BURLETES Y TAPAJUNTAS ', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    
INSERT INTO FAMILIA_PRODUCTO VALUES(FAMILIA_PRODUCTO_SEQ.NEXTVAL, 'Pintura', 'product-family/pintura.jpg');
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'ADHESIVOS, COLAS Y PEGAMENTOS', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'AISLAMIENTO E IMPREMEABILIZACIÓN', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'ÚTILES DE PINTURA', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'CENTRO DE COLOR TINTOMÉTRICO', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'LIMPIEZA', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'PINTURA PLÁSTICA', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'ESMALTES', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'ESPECIALES', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'TRATAMIENTO PARA LA MADERA', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'TRATAMIENTO PARA EL METAL', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    
INSERT INTO FAMILIA_PRODUCTO VALUES(FAMILIA_PRODUCTO_SEQ.NEXTVAL, 'Decoración', 'product-family/decoracion.jpg');
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'DECORACIÓN TECHO', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'DECORACIÓN MURAL', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'DECORACIÓN SUELO', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'DECORACIÓN VENTANA', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'TEXTIL', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'ENMARCADO', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'DECORACIÓN NAVIDEÑA', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'COMPLEMENTOS DECORATIVOS ', FAMILIA_PRODUCTO_SEQ.CURRVAL);
 
INSERT INTO FAMILIA_PRODUCTO VALUES(FAMILIA_PRODUCTO_SEQ.NEXTVAL, 'Mobiliario y ordenación', 'product-family/mobiliario.jpg');
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'ESTANTERÍAS', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'ARMARIOS', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'MESAS', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'SILLAS', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'ZAPATEROS', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'SOFÁS Y SILLONES', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'CAJAS PARA ORDENAR ', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'MOBILIARIOS AUXILIAR', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'SOPORTES Y ESTANTES', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'CAMAS', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    
INSERT INTO FAMILIA_PRODUCTO VALUES(FAMILIA_PRODUCTO_SEQ.NEXTVAL, 'Climatización', 'product-family/climatizacion.jpg');
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'AIRE ACONDICIONADO', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'VENTILACIÓN', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'AMBIENTAL ELÉCTRICO', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'INSTALACIÓN', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'COMBUSTIÓN', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'TRATAMIENTO AIRE', FAMILIA_PRODUCTO_SEQ.CURRVAL);
    INSERT INTO TIPO_PRODUCTO VALUES(TIPO_PRODUCTO_SEQ.NEXTVAL, 'CONDUCCIÓN DEL AIRE', FAMILIA_PRODUCTO_SEQ.CURRVAL);
