-------------------------- TRIGGERS PARA CAMPOS AUTOFIELD DJANGO --------------------------
CREATE OR REPLACE TRIGGER DOMICILIO_TRIGGER
    BEFORE INSERT ON DOMICILIO
    FOR EACH ROW
BEGIN
    SELECT DOMICILIO_SEQ.NEXTVAL
        INTO :NEW.ID_DOMICILIO 
    FROM DUAL;
END;