-- TRIGGER PARA CAMPOS AUTOFIELDS DJANGO

CREATE SEQUENCE DOMICILIO_SEQ;

CREATE OR REPLACE TRIGGER ADRESS_TRIGGER
  BEFORE INSERT ON DOMICILIO
  FOR EACH ROW
BEGIN
  SELECT DOMICILIO_SEQ.NEXTVAL
    INTO :NEW.ID_DOMICILIO 
    FROM DUAL;
END;