# Generated by Django 3.2 on 2021-04-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('comuna', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id_domicilio', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=200)),
                ('nro', models.FloatField()),
                ('nro_departamento', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'domicilio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FamiliaProducto',
            fields=[
                ('id_familia_producto', models.AutoField(primary_key=True, serialize=False)),
                ('familia_producto', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'familia_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('nro_nota_credito', models.FloatField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'nota_credito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotaCreditoDetalle',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.FloatField()),
            ],
            options={
                'db_table': 'nota_credito_detalle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OcDetalle',
            fields=[
                ('id_oc_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.FloatField()),
            ],
            options={
                'db_table': 'oc_detalle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id_orden_compra', models.FloatField(primary_key=True, serialize=False)),
                ('total', models.FloatField()),
            ],
            options={
                'db_table': 'orden_compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('rut_persona', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('celular', models.FloatField()),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('precio', models.FloatField()),
                ('stock', models.FloatField()),
                ('stock_critico', models.FloatField()),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.FloatField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('provincia', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'provincia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('nro_doc', models.FloatField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('subtotal', models.FloatField()),
                ('iva', models.FloatField()),
                ('total', models.FloatField()),
            ],
            options={
                'db_table': 'recibo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReciboDetalle',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.FloatField()),
            ],
            options={
                'db_table': 'recibo_detalle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id_rubro', models.AutoField(primary_key=True, serialize=False)),
                ('rubro', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'rubro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo_doc', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_doc', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDomicilio',
            fields=[
                ('id_tipo_domicilio', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_domicilio', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_domicilio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id_tipo_producto', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_producto', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tipo_producto',
                'managed': False,
            },
        ),
    ]
