# Generated by Django 3.2 on 2021-05-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.FloatField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'marca',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='comuna',
            options={'managed': False, 'ordering': ['comuna']},
        ),
    ]
