# Generated by Django 3.2.2 on 2021-05-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210503_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='NcDetalle',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.FloatField()),
                ('total', models.FloatField()),
            ],
            options={
                'db_table': 'nc_detalle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('nro_orden', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('total', models.FloatField()),
            ],
            options={
                'db_table': 'orden',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenDetalle',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.FloatField()),
                ('total', models.FloatField()),
            ],
            options={
                'db_table': 'orden_detalle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoOrden',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_orden',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='NotaCreditoDetalle',
        ),
        migrations.DeleteModel(
            name='OcDetalle',
        ),
        migrations.DeleteModel(
            name='OrdenCompra',
        ),
        migrations.DeleteModel(
            name='ReciboDetalle',
        ),
    ]
